apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: flink-tutorial
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.bind-host: 0.0.0.0
    taskmanager.bind-host: 0.0.0.0
    taskmanager.numberOfTaskSlots: 4
    parallelism.default: 2
    blob.server.port: 6124
    queryable-state.proxy.ports: 6125
    rest.bind-address: 0.0.0.0
    rest.address: 0.0.0.0
    rest.port: 8081
    web.submit.enable: true
    web.cancel.enable: true
    classloader.check-leaked-classloader: false
  log4j-console.properties: |+
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
